tinymce.addI18n('id',{
"Cut": "Potong",
"Header 2": "Header 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Browser anda tidak mendukung akses langsung ke clipboard. Silahkan gunakan Ctrl+X\/C\/V dari keyboard.",
"Div": "Div",
"Paste": "Tempel",
"Close": "Tutup",
"Font Family": "Keluarga Huruf",
"Pre": "Pre",
"Align right": "Rata kanan",
"New document": "Dokumen baru",
"Blockquote": "Kutipan",
"Numbered list": "Daftar bernomor",
"Increase indent": "Tambah inden",
"Formats": "Format",
"Headers": "Header",
"Select all": "Pilih semua",
"Header 3": "Header 3",
"Blocks": "Blok",
"Undo": "Batalkan",
"Strikethrough": "Coret-tengah",
"Bullet list": "Daftar simbol",
"Header 1": "Header 1",
"Superscript": "Superskrip",
"Clear formatting": "Bersihkan format",
"Font Sizes": "Ukuran Huruf",
"Subscript": "Subskrip",
"Header 6": "Header 6",
"Redo": "Ulangi",
"Paragraph": "Paragraf",
"Ok": "Oke",
"Bold": "Tebal",
"Code": "Kode",
"Italic": "Miring",
"Align center": "Rata tengah",
"Header 5": "Header 5",
"Decrease indent": "Kurangi inden",
"Header 4": "Header 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "'Tempel' sedang dalam modus teks polos. Isi akan ditempelkan sebagai teks polos hingga anda mematikan pilihan ini.",
"Underline": "Garis bawah",
"Cancel": "Batal",
"Justify": "Ratakan",
"Inline": "Sebaris",
"Copy": "Salin",
"Align left": "Rata kiri",
"Visual aids": "Alat bantu visual",
"Lower Greek": "Huruf Yunani kecil",
"Square": "Kotak",
"Default": "Baku",
"Lower Alpha": "Huruf kecil",
"Circle": "Lingkatan",
"Disc": "Cakram",
"Upper Alpha": "Huruf besar",
"Upper Roman": "Romawi besar",
"Lower Roman": "Romawi kecil",
"Name": "Nama",
"Anchor": "Jangkar",
"You have unsaved changes are you sure you want to navigate away?": "Perubahan belum tersimpan, yakin akan meninggalkan?",
"Restore last draft": "Kembalikan naskah terakhir",
"Special character": "Karakter spesial",
"Source code": "Kode sumber",
"Right to left": "Kanan ke kiri",
"Left to right": "Kiri ke kanan",
"Emoticons": "Emotikon",
"Robots": "Robot",
"Document properties": "Properti dokumen",
"Title": "Judul",
"Keywords": "Kata kunci",
"Encoding": "Enkoding",
"Description": "Deskripsi",
"Author": "Penulis",
"Fullscreen": "Layar-penuh",
"Horizontal line": "Garis horisontal",
"Horizontal space": "Spasi horisontal",
"Insert\/edit image": "Sisipkan\/sunting gambar",
"General": "Umum",
"Advanced": "Mahir",
"Source": "Sumber",
"Border": "Tepi",
"Constrain proportions": "Tetap proporsi",
"Vertical space": "Spasi vertikal",
"Image description": "Deskripsi gambar",
"Style": "Gaya",
"Dimensions": "Dimensi",
"Insert image": "Sisipkan gambar",
"Insert date\/time": "Sisipkan tanggal\/jam",
"Remove link": "Hapus pintasan",
"Url": "URL",
"Text to display": "Teks ditampilkan",
"Anchors": "Jangkar",
"Insert link": "Sisipkan pintasan",
"New window": "Jendela baru",
"None": "Tidak-ada",
"Target": "Target",
"Insert\/edit link": "Sisipkan\/sunting pintasan",
"Insert\/edit video": "Sisipkan\/sunting video",
"Poster": "Poster",
"Alternative source": "Sumber alternatif",
"Paste your embed code below:": "Tempelkan kode embed di bawah:",
"Insert video": "Sisipkan video",
"Embed": "Embed",
"Nonbreaking space": "Spasi non-penggal",
"Page break": "Pindah halaman",
"Paste as text": "Tempel sebagai teks",
"Preview": "Pra-tinjau",
"Print": "Cetak",
"Save": "Simpan",
"Could not find the specified string.": "Tidak dapat menemukan kata yang ditentukan.",
"Replace": "Tindas",
"Next": "Berikut",
"Whole words": "Kata Utuh",
"Find and replace": "Cari dan tindas",
"Replace with": "Tindas dengan",
"Find": "Cari",
"Replace all": "Tindas semua",
"Match case": "Cocokan bentuk",
"Prev": "Sebelum",
"Spellcheck": "Periksa-ejaan",
"Finish": "Selesai",
"Ignore all": "Abaikan semua",
"Ignore": "Abaikan",
"Insert row before": "Sisipkan baris sebelumnya",
"Rows": "Baris",
"Height": "Tinggi",
"Paste row after": "Tempelkan baris sesudahnya",
"Alignment": "Perataan",
"Column group": "Grup kolom",
"Row": "Baris",
"Insert column before": "Sisipkan kolom sebelumnya",
"Split cell": "Pisahkan sel",
"Cell padding": "Padding sel",
"Cell spacing": "Spasi sel",
"Row type": "Tipe baris",
"Insert table": "Sisipkan tabel",
"Body": "Bodi",
"Caption": "Caption",
"Footer": "Footer",
"Delete row": "Hapus baris",
"Paste row before": "Tempelkan baris sebelumnya",
"Scope": "Lingkup",
"Delete table": "Hapus tabel",
"Header cell": "Sel Header",
"Column": "Kolom",
"Cell": "Sel",
"Header": "Header",
"Cell type": "Tipe sel",
"Copy row": "Salin baris",
"Row properties": "Properti baris",
"Table properties": "Properti tabel",
"Row group": "Grup baris",
"Right": "Kanan",
"Insert column after": "Sisipkan kolom sesudahnya",
"Cols": "Kolom",
"Insert row after": "Sisipkan baris sesudahnya",
"Width": "Lebar",
"Cell properties": "Properti sel",
"Left": "Kiri",
"Cut row": "Potong baris",
"Delete column": "Hapus kolom",
"Center": "Tengah",
"Merge cells": "Gabung sel",
"Insert template": "Sisipkan template",
"Templates": "Template",
"Background color": "Warna latar",
"Text color": "Warna teks",
"Show blocks": "Tampilkan blok",
"Show invisible characters": "Tampilkan karakter tak-terlihat",
"Words: {0}": "Kata: {0}",
"Insert": "Sisip",
"File": "Berkas",
"Edit": "Sunting",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Area Rich Text. Tekan ALT-F9 untuk menu. Tekan ALT-F10 untuk toolbar. Tekan ALT-0 untuk bantuan",
"Tools": "Alat",
"View": "Tampilan",
"Table": "Tabel",
"Format": "Format"
});